services:
  - type: web
    name: flask-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "/opt/render/.local/bin/gunicorn --bind 0.0.0.0:$PORT run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0  # Usa la misma versión que en tu Dockerfile