services:
  - type: web
    name: flask-api
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "/opt/render/.local/bin/gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 2.3.2